In [35]:
import pandas as pd
import glob

path = r'D:\Data_Project\Drug_Data_Years_Zach' # use your path
all_files = glob.glob(path + "/*.csv")


df_from_each_file = (pd.read_csv(f) for f in all_files)
concatenated_df   = pd.concat(df_from_each_file, ignore_index=True, sort=True)

concatenated_df.head()

,age_group,ci_lower,ci_upper,estimate,geography,outcome,year_pair,years
0,12 or Older,0.561499,0.622287,0.592246,Colorado,Alcohol Use in the Past Month,2002-03,NaN
1,12 or Older,0.555057,0.619857,0.587838,Colorado,Alcohol Use in the Past Month,2003-04,NaN
2,12 or Older,0.562016,0.625712,0.594260,Colorado,Alcohol Use in the Past Month,2004-05,NaN
3,12 or Older,0.554280,0.617521,0.586256,Colorado,Alcohol Use in the Past Month,2005-06,NaN
4,12 or Older,0.567890,0.631256,0.599991,Colorado,Alcohol Use in the Past Month,2006-07,NaN

In [36]:
concatenated_df.count()

age_group    317
ci_lower     317
ci_upper     317
estimate     317
geography    317
outcome      317
year_pair    285
years         32
dtype: int64

In [40]:
outcome_df = concatenated_df.set_index(['outcome'])
outcome_df

,age_group,ci_lower,ci_upper,estimate,geography,year_pair,years
outcome,,,,,,,
Alcohol Use in the Past Month,12 or Older,0.561499,0.622287,0.592246,Colorado,2002-03,NaN
Alcohol Use in the Past Month,12 or Older,0.555057,0.619857,0.587838,Colorado,2003-04,NaN
Alcohol Use in the Past Month,12 or Older,0.562016,0.625712,0.594260,Colorado,2004-05,NaN
Alcohol Use in the Past Month,12 or Older,0.554280,0.617521,0.586256,Colorado,2005-06,NaN
Alcohol Use in the Past Month,12 or Older,0.567890,0.631256,0.599991,Colorado,2006-07,NaN
Alcohol Use in the Past Month,12 or Older,0.590627,0.651325,0.621451,Colorado,2007-08,NaN
Alcohol Use in the Past Month,12 or Older,0.591432,0.651980,0.622182,Colorado,2008-09,NaN
Alcohol Use in the Past Month,12 or Older,0.593090,0.659292,0.626784,Colorado,2009-10,NaN
Alcohol Use in the Past Month,12 or Older,0.582345,0.645597,0.614454,Colorado,2010-11,NaN
Alcohol Use in the Past Month,12 or Older,0.560483,0.622751,0.591986,Colorado,2011-12,NaN
Alcohol Use in the Past Month,12 or Older,0.579449,0.640384,0.610347,Colorado,2012-13,NaN
Alcohol Use in the Past Month,12 or Older,0.586914,0.643424,0.615559,Colorado,2013-14,NaN
Alcohol Use in the Past Month,12 or Older,0.564005,0.619741,0.592170,Colorado,2014-15,NaN
Alcohol Use in the Past Month,12 or Older,0.546564,0.603500,0.575282,Colorado,2015-16,NaN
Alcohol Use in the Past Month,12 or Older,0.567720,0.621335,0.594810,Colorado,2016-17,NaN
Alcohol Use in the Past Month,12 or Older,0.456392,0.489053,0.472693,Texas,2002-03,NaN
Alcohol Use in the Past Month,12 or Older,0.450918,0.484447,0.467646,Texas,2003-04,NaN
Alcohol Use in the Past Month,12 or Older,0.469067,0.503322,0.486178,Texas,2004-05,NaN
Alcohol Use in the Past Month,12 or Older,0.478511,0.511723,0.495112,Texas,2005-06,NaN
Alcohol Use in the Past Month,12 or Older,0.460415,0.493553,0.476959,Texas,2006-07,NaN
Alcohol Use in the Past Month,12 or Older,0.453698,0.487089,0.470360,Texas,2007-08,NaN
Alcohol Use in the Past Month,12 or Older,0.466582,0.501884,0.484213,Texas,2008-09,NaN
Alcohol Use in the Past Month,12 or Older,0.472440,0.510489,0.491452,Texas,2009-10,NaN
Alcohol Use in the Past Month,12 or Older,0.478449,0.513743,0.496091,Texas,2010-11,NaN
Alcohol Use in the Past Month,12 or Older,0.465020,0.498828,0.481903,Texas,2011-12,NaN
Alcohol Use in the Past Month,12 or Older,0.451408,0.482830,0.467086,Texas,2012-13,NaN
Alcohol Use in the Past Month,12 or Older,0.457182,0.488336,0.472732,Texas,2013-14,NaN
Alcohol Use in the Past Month,12 or Older,0.464263,0.493740,0.478983,Texas,2014-15,NaN
Alcohol Use in the Past Month,12 or Older,0.457286,0.485601,0.471420,Texas,2015-16,NaN
Alcohol Use in the Past Month,12 or Older,0.457195,0.485314,0.471232,Texas,2016-17,NaN
...,...,...,...,...,...,...,...
Marijuana Use in the Past Month,18 to 25,0.281558,0.355664,0.317456,Colorado,2014-15,NaN
Marijuana Use in the Past Month,18 to 25,0.281553,0.365201,0.321952,Colorado,2015-16,NaN
Marijuana Use in the Past Month,18 to 25,0.276741,0.361038,0.317394,Colorado,2016-17,NaN
Marijuana Use in the Past Month,26 or Older,0.045223,0.079513,0.060119,Colorado,2002-03,NaN
Marijuana Use in the Past Month,26 or Older,0.036965,0.066029,0.049513,Colorado,2003-04,NaN
Marijuana Use in the Past Month,26 or Older,0.037296,0.065076,0.049365,Colorado,2004-05,NaN
Marijuana Use in the Past Month,26 or Older,0.041886,0.070569,0.054475,Colorado,2005-06,NaN
Marijuana Use in the Past Month,26 or Older,0.045011,0.074687,0.058096,Colorado,2006-07,NaN
Marijuana Use in the Past Month,26 or Older,0.052290,0.089027,0.068407,Colorado,2007-08,NaN
Marijuana Use in the Past Month,26 or Older,0.055720,0.095348,0.073098,Colorado,2008-09,NaN
Marijuana Use in the Past Month,26 or Older,0.069646,0.112039,0.088579,Colorado,2009-10,NaN
Marijuana Use in the Past Month,26 or Older,0.064283,0.103786,0.081890,Colorado,2010-11,NaN
Marijuana Use in the Past Month,26 or Older,0.059141,0.097989,0.076328,Colorado,2011-12,NaN
Marijuana Use in the Past Month,26 or Older,0.080841,0.126178,0.101280,Colorado,2012-13,NaN
Marijuana Use in the Past Month,26 or Older,0.102793,0.149969,0.124476,Colorado,2013-14,NaN
Marijuana Use in the Past Month,26 or Older,0.124148,0.172059,0.146488,Colorado,2014-15,NaN
Marijuana Use in the Past Month,26 or Older,0.119272,0.163771,0.140049,Colorado,2015-16,NaN
Marijuana Use in the Past Month,26 or Older,0.126122,0.173054,0.148058,Colorado,2016-17,NaN
Had Serious Thoughts of Suicide in the Past Year,18 or Older,0.034022,0.052204,0.042186,Colorado,NaN,2008-10
Had Serious Thoughts of Suicide in the Past Year,18 or Older,0.030192,0.045254,0.036993,Colorado,NaN,2010-12
Had Serious Thoughts of Suicide in the Past Year,18 or Older,0.033444,0.048058,0.040118,Colorado,NaN,2012-14
Had Serious Thoughts of Suicide in the Past Year,18 or Older,0.040201,0.058103,0.048372,Colorado,NaN,2014-16
Had Serious Thoughts of Suicide in the Past Year,18 to 25,0.052742,0.077695,0.064096,Colorado,NaN,2008-10
Had Serious Thoughts of Suicide in the Past Year,18 to 25,0.055543,0.081615,0.067419,Colorado,NaN,2010-12
Had Serious Thoughts of Suicide in the Past Year,18 to 25,0.060043,0.088200,0.072879,Colorado,NaN,2012-14
Had Serious Thoughts of Suicide in the Past Year,18 to 25,0.074630,0.107078,0.089537,Colorado,NaN,2014-16
Had Serious Thoughts of Suicide in the Past Year,26 or Older,0.029648,0.049764,0.038463,Colorado,NaN,2008-10
Had Serious Thoughts of Suicide in the Past Year,26 or Older,0.024460,0.041355,0.031841,Colorado,NaN,2010-12
Had Serious Thoughts of Suicide in the Past Year,26 or Older,0.027281,0.043806,0.034604,Colorado,NaN,2012-14
Had Serious Thoughts of Suicide in the Past Year,26 or Older,0.032871,0.052208,0.041474,Colorado,NaN,2014-16